//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class Client {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param id (optional) 
     * @return Success
     */
    dependencyInstances(id: number | undefined): Observable<DependencyInstanceDetailVm> {
        let url_ = this.baseUrl + "/api/DependencyInstances?";
        if (id === null)
            throw new Error("The parameter 'id' cannot be null.");
        else if (id !== undefined)
            url_ += "Id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDependencyInstances(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDependencyInstances(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DependencyInstanceDetailVm>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DependencyInstanceDetailVm>;
        }));
    }

    protected processDependencyInstances(response: HttpResponseBase): Observable<DependencyInstanceDetailVm> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DependencyInstanceDetailVm.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    search(body: SearchDependencyInstancesWithPaginationQuery | undefined): Observable<DependencyInstanceVmPaginatedList> {
        let url_ = this.baseUrl + "/api/DependencyInstances/Search";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearch(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearch(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DependencyInstanceVmPaginatedList>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DependencyInstanceVmPaginatedList>;
        }));
    }

    protected processSearch(response: HttpResponseBase): Observable<DependencyInstanceVmPaginatedList> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DependencyInstanceVmPaginatedList.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param query (optional) 
     * @return Success
     */
    projects(query: ListProjectsQuery | undefined): Observable<ProjectsVm> {
        let url_ = this.baseUrl + "/api/Projects?";
        if (query === null)
            throw new Error("The parameter 'query' cannot be null.");
        else if (query !== undefined)
            url_ += "query=" + encodeURIComponent("" + query) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processProjects(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processProjects(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ProjectsVm>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ProjectsVm>;
        }));
    }

    protected processProjects(response: HttpResponseBase): Observable<ProjectsVm> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ProjectsVm.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param repositoryIds (optional) 
     * @return Success
     */
    getByRepositoryIds(repositoryIds: number[] | undefined): Observable<ProjectsVm> {
        let url_ = this.baseUrl + "/api/Projects/GetByRepositoryIds?";
        if (repositoryIds === null)
            throw new Error("The parameter 'repositoryIds' cannot be null.");
        else if (repositoryIds !== undefined)
            repositoryIds && repositoryIds.forEach(item => { url_ += "RepositoryIds=" + encodeURIComponent("" + item) + "&"; });
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetByRepositoryIds(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetByRepositoryIds(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ProjectsVm>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ProjectsVm>;
        }));
    }

    protected processGetByRepositoryIds(response: HttpResponseBase): Observable<ProjectsVm> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ProjectsVm.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param query (optional) 
     * @return Success
     */
    repositories(query: ListRepositoriesQuery | undefined): Observable<RepositoriesVm> {
        let url_ = this.baseUrl + "/api/Repositories?";
        if (query === null)
            throw new Error("The parameter 'query' cannot be null.");
        else if (query !== undefined)
            url_ += "query=" + encodeURIComponent("" + query) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRepositories(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRepositories(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<RepositoriesVm>;
                }
            } else
                return _observableThrow(response_) as any as Observable<RepositoriesVm>;
        }));
    }

    protected processRepositories(response: HttpResponseBase): Observable<RepositoriesVm> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = RepositoriesVm.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param sourceId (optional) 
     * @return Success
     */
    getBySourceId(sourceId: number | undefined): Observable<RepositoriesVm> {
        let url_ = this.baseUrl + "/api/Repositories/GetBySourceId?";
        if (sourceId === null)
            throw new Error("The parameter 'sourceId' cannot be null.");
        else if (sourceId !== undefined)
            url_ += "SourceId=" + encodeURIComponent("" + sourceId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetBySourceId(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetBySourceId(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<RepositoriesVm>;
                }
            } else
                return _observableThrow(response_) as any as Observable<RepositoriesVm>;
        }));
    }

    protected processGetBySourceId(response: HttpResponseBase): Observable<RepositoriesVm> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = RepositoriesVm.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param query (optional) 
     * @return Success
     */
    sources(query: ListSourcesQuery | undefined): Observable<SourcesVm> {
        let url_ = this.baseUrl + "/api/Sources?";
        if (query === null)
            throw new Error("The parameter 'query' cannot be null.");
        else if (query !== undefined)
            url_ += "query=" + encodeURIComponent("" + query) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSources(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSources(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SourcesVm>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SourcesVm>;
        }));
    }

    protected processSources(response: HttpResponseBase): Observable<SourcesVm> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SourcesVm.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class DependencyInstanceDetailVm implements IDependencyInstanceDetailVm {
    id?: number;
    source?: string | undefined;
    name?: string | undefined;
    version?: string | undefined;
    repositories?: RepositoryDetailVm[] | undefined;

    constructor(data?: IDependencyInstanceDetailVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.source = _data["source"];
            this.name = _data["name"];
            this.version = _data["version"];
            if (Array.isArray(_data["repositories"])) {
                this.repositories = [] as any;
                for (let item of _data["repositories"])
                    this.repositories!.push(RepositoryDetailVm.fromJS(item));
            }
        }
    }

    static fromJS(data: any): DependencyInstanceDetailVm {
        data = typeof data === 'object' ? data : {};
        let result = new DependencyInstanceDetailVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["source"] = this.source;
        data["name"] = this.name;
        data["version"] = this.version;
        if (Array.isArray(this.repositories)) {
            data["repositories"] = [];
            for (let item of this.repositories)
                data["repositories"].push(item.toJSON());
        }
        return data;
    }
}

export interface IDependencyInstanceDetailVm {
    id?: number;
    source?: string | undefined;
    name?: string | undefined;
    version?: string | undefined;
    repositories?: RepositoryDetailVm[] | undefined;
}

export class DependencyInstanceVm implements IDependencyInstanceVm {
    source?: string | undefined;
    name?: string | undefined;
    version?: string | undefined;

    constructor(data?: IDependencyInstanceVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.source = _data["source"];
            this.name = _data["name"];
            this.version = _data["version"];
        }
    }

    static fromJS(data: any): DependencyInstanceVm {
        data = typeof data === 'object' ? data : {};
        let result = new DependencyInstanceVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["source"] = this.source;
        data["name"] = this.name;
        data["version"] = this.version;
        return data;
    }
}

export interface IDependencyInstanceVm {
    source?: string | undefined;
    name?: string | undefined;
    version?: string | undefined;
}

export class DependencyInstanceVmPaginatedList implements IDependencyInstanceVmPaginatedList {
    readonly items?: DependencyInstanceVm[] | undefined;
    readonly pageNumber?: number;
    readonly totalPages?: number;
    readonly totalCount?: number;
    readonly hasPreviousPage?: boolean;
    readonly hasNextPage?: boolean;

    constructor(data?: IDependencyInstanceVmPaginatedList) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                (<any>this).items = [] as any;
                for (let item of _data["items"])
                    (<any>this).items!.push(DependencyInstanceVm.fromJS(item));
            }
            (<any>this).pageNumber = _data["pageNumber"];
            (<any>this).totalPages = _data["totalPages"];
            (<any>this).totalCount = _data["totalCount"];
            (<any>this).hasPreviousPage = _data["hasPreviousPage"];
            (<any>this).hasNextPage = _data["hasNextPage"];
        }
    }

    static fromJS(data: any): DependencyInstanceVmPaginatedList {
        data = typeof data === 'object' ? data : {};
        let result = new DependencyInstanceVmPaginatedList();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item.toJSON());
        }
        data["pageNumber"] = this.pageNumber;
        data["totalPages"] = this.totalPages;
        data["totalCount"] = this.totalCount;
        data["hasPreviousPage"] = this.hasPreviousPage;
        data["hasNextPage"] = this.hasNextPage;
        return data;
    }
}

export interface IDependencyInstanceVmPaginatedList {
    items?: DependencyInstanceVm[] | undefined;
    pageNumber?: number;
    totalPages?: number;
    totalCount?: number;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
}

export enum FilterOperator {
    _0 = 0,
    _1 = 1,
}

export class ListProjectsQuery implements IListProjectsQuery {

    constructor(data?: IListProjectsQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): ListProjectsQuery {
        data = typeof data === 'object' ? data : {};
        let result = new ListProjectsQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IListProjectsQuery {
}

export class ListRepositoriesQuery implements IListRepositoriesQuery {

    constructor(data?: IListRepositoriesQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): ListRepositoriesQuery {
        data = typeof data === 'object' ? data : {};
        let result = new ListRepositoriesQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IListRepositoriesQuery {
}

export class ListSourcesQuery implements IListSourcesQuery {

    constructor(data?: IListSourcesQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): ListSourcesQuery {
        data = typeof data === 'object' ? data : {};
        let result = new ListSourcesQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IListSourcesQuery {
}

export enum MatchMode {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
}

export class PaginatedFilter implements IPaginatedFilter {
    matchMode?: MatchMode;
    operator?: FilterOperator;
    value?: string | undefined;

    constructor(data?: IPaginatedFilter) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.matchMode = _data["matchMode"];
            this.operator = _data["operator"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): PaginatedFilter {
        data = typeof data === 'object' ? data : {};
        let result = new PaginatedFilter();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["matchMode"] = this.matchMode;
        data["operator"] = this.operator;
        data["value"] = this.value;
        return data;
    }
}

export interface IPaginatedFilter {
    matchMode?: MatchMode;
    operator?: FilterOperator;
    value?: string | undefined;
}

export class ProjectDetailVm implements IProjectDetailVm {
    id?: number;
    name?: string | undefined;
    version?: string | undefined;

    constructor(data?: IProjectDetailVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.version = _data["version"];
        }
    }

    static fromJS(data: any): ProjectDetailVm {
        data = typeof data === 'object' ? data : {};
        let result = new ProjectDetailVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["version"] = this.version;
        return data;
    }
}

export interface IProjectDetailVm {
    id?: number;
    name?: string | undefined;
    version?: string | undefined;
}

export class ProjectVm implements IProjectVm {
    id?: number;
    name?: string | undefined;
    version?: string | undefined;
    dependencyCount?: number;
    repositoryId?: number;
    repositoryName?: string | undefined;

    constructor(data?: IProjectVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.version = _data["version"];
            this.dependencyCount = _data["dependencyCount"];
            this.repositoryId = _data["repositoryId"];
            this.repositoryName = _data["repositoryName"];
        }
    }

    static fromJS(data: any): ProjectVm {
        data = typeof data === 'object' ? data : {};
        let result = new ProjectVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["version"] = this.version;
        data["dependencyCount"] = this.dependencyCount;
        data["repositoryId"] = this.repositoryId;
        data["repositoryName"] = this.repositoryName;
        return data;
    }
}

export interface IProjectVm {
    id?: number;
    name?: string | undefined;
    version?: string | undefined;
    dependencyCount?: number;
    repositoryId?: number;
    repositoryName?: string | undefined;
}

export class ProjectsVm implements IProjectsVm {
    projects?: ProjectVm[] | undefined;

    constructor(data?: IProjectsVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["projects"])) {
                this.projects = [] as any;
                for (let item of _data["projects"])
                    this.projects!.push(ProjectVm.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProjectsVm {
        data = typeof data === 'object' ? data : {};
        let result = new ProjectsVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.projects)) {
            data["projects"] = [];
            for (let item of this.projects)
                data["projects"].push(item.toJSON());
        }
        return data;
    }
}

export interface IProjectsVm {
    projects?: ProjectVm[] | undefined;
}

export class RepositoriesVm implements IRepositoriesVm {
    repositories?: RepositoryVm[] | undefined;

    constructor(data?: IRepositoriesVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["repositories"])) {
                this.repositories = [] as any;
                for (let item of _data["repositories"])
                    this.repositories!.push(RepositoryVm.fromJS(item));
            }
        }
    }

    static fromJS(data: any): RepositoriesVm {
        data = typeof data === 'object' ? data : {};
        let result = new RepositoriesVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.repositories)) {
            data["repositories"] = [];
            for (let item of this.repositories)
                data["repositories"].push(item.toJSON());
        }
        return data;
    }
}

export interface IRepositoriesVm {
    repositories?: RepositoryVm[] | undefined;
}

export class RepositoryDetailVm implements IRepositoryDetailVm {
    id?: number;
    name?: string | undefined;
    projects?: ProjectDetailVm[] | undefined;

    constructor(data?: IRepositoryDetailVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            if (Array.isArray(_data["projects"])) {
                this.projects = [] as any;
                for (let item of _data["projects"])
                    this.projects!.push(ProjectDetailVm.fromJS(item));
            }
        }
    }

    static fromJS(data: any): RepositoryDetailVm {
        data = typeof data === 'object' ? data : {};
        let result = new RepositoryDetailVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        if (Array.isArray(this.projects)) {
            data["projects"] = [];
            for (let item of this.projects)
                data["projects"].push(item.toJSON());
        }
        return data;
    }
}

export interface IRepositoryDetailVm {
    id?: number;
    name?: string | undefined;
    projects?: ProjectDetailVm[] | undefined;
}

export class RepositoryVm implements IRepositoryVm {
    id?: number;
    name?: string | undefined;
    remoteUrl?: string | undefined;
    defaultBranchName?: string | undefined;
    parseTime?: Date;

    constructor(data?: IRepositoryVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.remoteUrl = _data["remoteUrl"];
            this.defaultBranchName = _data["defaultBranchName"];
            this.parseTime = _data["parseTime"] ? new Date(_data["parseTime"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): RepositoryVm {
        data = typeof data === 'object' ? data : {};
        let result = new RepositoryVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["remoteUrl"] = this.remoteUrl;
        data["defaultBranchName"] = this.defaultBranchName;
        data["parseTime"] = this.parseTime ? this.parseTime.toISOString() : <any>undefined;
        return data;
    }
}

export interface IRepositoryVm {
    id?: number;
    name?: string | undefined;
    remoteUrl?: string | undefined;
    defaultBranchName?: string | undefined;
    parseTime?: Date;
}

export class SearchDependencyInstancesWithPaginationQuery implements ISearchDependencyInstancesWithPaginationQuery {
    pageNumber?: number;
    pageSize?: number;
    sortField?: string | undefined;
    sortOrder?: SortOrder;
    filters?: { [key: string]: PaginatedFilter[]; } | undefined;
    sourceIds?: number[] | undefined;
    repositoryIds?: number[] | undefined;
    projectIds?: number[] | undefined;

    constructor(data?: ISearchDependencyInstancesWithPaginationQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.pageNumber = _data["pageNumber"];
            this.pageSize = _data["pageSize"];
            this.sortField = _data["sortField"];
            this.sortOrder = _data["sortOrder"];
            if (_data["filters"]) {
                this.filters = {} as any;
                for (let key in _data["filters"]) {
                    if (_data["filters"].hasOwnProperty(key))
                        (<any>this.filters)![key] = _data["filters"][key] ? _data["filters"][key].map((i: any) => PaginatedFilter.fromJS(i)) : [];
                }
            }
            if (Array.isArray(_data["sourceIds"])) {
                this.sourceIds = [] as any;
                for (let item of _data["sourceIds"])
                    this.sourceIds!.push(item);
            }
            if (Array.isArray(_data["repositoryIds"])) {
                this.repositoryIds = [] as any;
                for (let item of _data["repositoryIds"])
                    this.repositoryIds!.push(item);
            }
            if (Array.isArray(_data["projectIds"])) {
                this.projectIds = [] as any;
                for (let item of _data["projectIds"])
                    this.projectIds!.push(item);
            }
        }
    }

    static fromJS(data: any): SearchDependencyInstancesWithPaginationQuery {
        data = typeof data === 'object' ? data : {};
        let result = new SearchDependencyInstancesWithPaginationQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["pageNumber"] = this.pageNumber;
        data["pageSize"] = this.pageSize;
        data["sortField"] = this.sortField;
        data["sortOrder"] = this.sortOrder;
        if (this.filters) {
            data["filters"] = {};
            for (let key in this.filters) {
                if (this.filters.hasOwnProperty(key))
                    (<any>data["filters"])[key] = (<any>this.filters)[key];
            }
        }
        if (Array.isArray(this.sourceIds)) {
            data["sourceIds"] = [];
            for (let item of this.sourceIds)
                data["sourceIds"].push(item);
        }
        if (Array.isArray(this.repositoryIds)) {
            data["repositoryIds"] = [];
            for (let item of this.repositoryIds)
                data["repositoryIds"].push(item);
        }
        if (Array.isArray(this.projectIds)) {
            data["projectIds"] = [];
            for (let item of this.projectIds)
                data["projectIds"].push(item);
        }
        return data;
    }
}

export interface ISearchDependencyInstancesWithPaginationQuery {
    pageNumber?: number;
    pageSize?: number;
    sortField?: string | undefined;
    sortOrder?: SortOrder;
    filters?: { [key: string]: PaginatedFilter[]; } | undefined;
    sourceIds?: number[] | undefined;
    repositoryIds?: number[] | undefined;
    projectIds?: number[] | undefined;
}

export enum SortOrder {
    _0 = 0,
    _1 = 1,
}

export class SourceVm implements ISourceVm {
    id?: number;
    name?: string | undefined;

    constructor(data?: ISourceVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): SourceVm {
        data = typeof data === 'object' ? data : {};
        let result = new SourceVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface ISourceVm {
    id?: number;
    name?: string | undefined;
}

export class SourcesVm implements ISourcesVm {
    sources?: SourceVm[] | undefined;

    constructor(data?: ISourcesVm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["sources"])) {
                this.sources = [] as any;
                for (let item of _data["sources"])
                    this.sources!.push(SourceVm.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SourcesVm {
        data = typeof data === 'object' ? data : {};
        let result = new SourcesVm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.sources)) {
            data["sources"] = [];
            for (let item of this.sources)
                data["sources"].push(item.toJSON());
        }
        return data;
    }
}

export interface ISourcesVm {
    sources?: SourceVm[] | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}